Admin product page sorting filter
GeorgeVragalev/nopCommerce pull request #3
Opened 2022-05-31 12:44 UTC by GeorgeVragalev

Sort products by their characteristics: Sort by Id, name, Price, Stock, SKU, published
Sorted using dropdown list

2022-05-31 12:50 UTC, denisburlacu requested changes

2022-05-31 12:50 UTC, denisburlacu commented on src/Libraries/Nop.Services/Catalog/ProductExtensions.cs
> +                // ProductSortingEnum.Position when productsQuery is IOrderedQueryable => productsQuery,
remove commented code

2022-05-31 12:50 UTC, denisburlacu commented on src/Presentation/Nop.Web/Nop.Web.csproj
> +    <PackageReference Include="AutoMapper.Extensions.EnumMapping" Version="1.1.0" />
remove this one

2022-05-31 12:50 UTC, denisburlacu commented on src/Presentation/Nop.Web/Areas/Admin/Factories/ProductModelFactory.cs
> +            // searchModel.OrderBy = command.OrderBy;
remove temporary comments

2022-05-31 13:09 UTC, roman-gherman commented on src/Libraries/Nop.Services/Catalog/ProductService.cs
> +                    var allIds =
remove the spaces

2022-05-31 13:09 UTC, roman-gherman commented on src/Presentation/Nop.Web/Areas/Admin/Factories/BaseAdminModelFactory.cs
> +
remove the spaces

2022-05-31 13:09 UTC, roman-gherman commented on src/Libraries/Nop.Services/Catalog/ProductService.cs
>                  return;
it is not a very good practice to reformat the entire file - it is hard to do review - creates a lot of noise

2022-05-31 13:09 UTC, roman-gherman commented on src/Presentation/Nop.Web/Areas/Admin/Infrastructure/Mapper/Extensions/MappingExtensions.cs
>              //use AutoMapper for mapping objects
avoid this kind of changes - try to review what you commit on git, before the commit

2022-06-06 08:07 UTC, denisburlacu requested changes

2022-06-06 08:07 UTC, denisburlacu commented on src/Presentation/Nop.Web/Areas/Admin/Controllers/ProductController.cs
> +        public virtual async Task<IActionResult> ViewById(int id)
rename to overciew

2022-06-06 08:07 UTC, denisburlacu commented on src/Presentation/Nop.Web/Areas/Admin/Controllers/ProductController.cs
> +            var productPicture = await _productService.GetProductPictureByIdAsync(model.Id)
how about the case when product will not have image at all, will this throw an exception?, because by design i can have a product without image

2022-06-06 08:07 UTC, denisburlacu commented on src/Presentation/Nop.Web/Areas/Admin/Controllers/ProductController.cs
> +            var picture = (await _pictureService.GetPictureByIdAsync(productPicture.PictureId))
same thing here, are you sure if product doens't have an image this will not throw an exception?

2022-06-06 08:07 UTC, denisburlacu commented on src/Presentation/Nop.Web/Areas/Admin/Models/Catalog/ProductSearchModel.cs
> +
remove empty line

2022-06-06 13:31 UTC, denisburlacu approved these changes

2022-06-06 13:32 UTC, merged